---

environments:
  - name: dev
    cluster:
      maxSize: 2

service:
  name: jesse-test
  memory: 100
  port: 80
  healthEndpoint: /aftp/index.html
  pathPatterns:
    - /*
  priority: 10
  pipeline:
    source:
      repo: jesseadams/aftp-mu
    build:
      image: aws/codebuild/ubuntu-base:14.04

pipeline:
  muBaseurl: http://lol.nope
